# Generated by Django 5.2.9 on 2025-12-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_conversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tool_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='tool_used',
            field=models.BooleanField(default=False),
        ),
    ]
